[package]
name = "oneshot-uniffi"
version = "0.1.5"
authors = ["Linus Färnstrand <faern@faern.net>"]
license = "MIT OR Apache-2.0"
readme = "README.md"

description = """
Patched version of oneshot specifically for the UniFFI project.

This removes the `loom` target and dependency which helps with UniFFI's downstream consumers.
"""

repository = "https://github.com/faern/oneshot"
keywords = ["oneshot", "spsc", "async", "sync", "channel"]
categories = ["asynchronous", "concurrency"]
edition = "2021"
rust-version = "1.60.0"

[features]
default = ["std", "async"]
# Enables usage of libstd. Adds support for thread blocking receive methods.
std = []
# Enables async receiving by implementing Future
async = []

[dev-dependencies]
criterion = "0.3"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "time"] }
async-std = { version = "1", features = ["attributes"] }

[[bench]]
name = "benches"
harness = false
